#!/usr/bin/env bash

echo "Running ruff check..."
ruff check . --config ruff.toml
if [ $? -ne 0 ]; then
    echo "ruff check failed. Fix errors before committing."
    exit 1
fi

echo "Running ruff format check..."
ruff format . --check --config ruff.toml
if [ $? -ne 0 ]; then
    echo "ruff format check failed. Run 'ruff format .' before committing."
    exit 1
fi
